#!/usr/share/ucs-test/runner bash
## desc: Checking for modified UCR templates
## tags:
##  - basic
##  - apptest
##  - python3
##  - performance
##  - nightly
## exposure: dangerous

# hard coded lowest number of successful tests below which this test fails
export SUCCESS_MIN=125


# Start markdown generation
cat <<"HEADER"
= Template migration status =
date $(date)
HEADER

# Install dependencies: We decided to do this within this script, because we
# can than simply delete it after the python3 migration has finished.
echo "== $0: Dependencies =="
which pip2 && pip2 -q install coverage
which pip3 && pip3 -q install coverage

if ! which asciidoctor; then
    apt-get -qq -y update
    apt-get -qq -y install asciidoctor
fi
echo ""
echo "== Overview =="
echo "The following table lists the current status of the python3 template migration"

if which coverage2 && which coverage3; then
    export PY2_COV=coverage2
    export PY3_COV=coverage3
else
    export PY2_COV=python2-coverage
    export PY3_COV=python3-coverage
fi

# safe the following awk script to disk:
cat <<"AWK" > /tmp/check-between.awk 
#!/usr/bin/env -S awk -f between.awk test.conf
BEGIN {
    # in order to behave as univention/config_registry/handler.py we have to
    # prepend each code section with a header, initialized as a string
    # variable:
    preamble = "# -*- coding: utf-8 -*-"                                    \
        "\n" "import univention.config_registry"                            \
        "\n" "configRegistry = univention.config_registry.ConfigRegistry()" \
        "\n" "configRegistry.load()"                                        \
        "\n" "# for compatibility"                                          \
        "\n" "baseConfig = configRegistry"
    exit_code = 0
}
END { exit exit_code }
# if start is 0 and we found a @!@-line: set start
!start && /@!@/ { start = 1 ; next }
# if start is set (and we still are within a code section) and there comes a @!@
start && /@!@/ {
    section++
    # write header and code into a file
    system("rm -f /tmp/cover.py")
    print preamble "\n" code > "/tmp/cover.py" ; close("/tmp/cover.py")
    # execute code coverage for python2. NOTE: debian has symlinked sh->dash,
    # awk uses sh to call any script, but we want bash
    cmd = "bash -c \"rm -f .coverage ;" \
          "$PY2_COV run --timid --include /tmp/cover.py /tmp/cover.py" \
          "  &>/tmp/py2.out && echo -n \|✅ || echo -n \|❎ ; echo -n \|" \
		  "&& printf '%s' $($PY2_COV report | egrep -o [0-9]+%\$ || echo 0%) \""
    print code | cmd ; close(cmd)
    # same thing (coverage) for python3. NOTE: egrep finds within the
    # coverage report the only line ending with a percent value
    cmd = "bash -c \"rm -f .coverage ;" \
          "$PY3_COV run --timid --include /tmp/cover.py /tmp/cover.py" \
          "  &>/tmp/py3.out && echo -n \|✅ || echo -n \|❎ ; echo -n \| " \
		  "&& printf '%s' $($PY3_COV report | egrep -o [0-9]+%\$ || echo 0%) \""
    print code | cmd ; close(cmd)
    # compare what output both runs produced and if diff returns with an exit
    # code unequal to zero it means that there were differences in both files
    if (system("diff -q /tmp/py[23].out 2>&1 >/dev/null") == 0) {
        printf "|✅"
    } else {
        printf "|❎"
        exit_code=127
    }
 
    # number of lines contained
    printf "|% 4d", lines
    # the package that installed the file
    printf "|%s", package
    # filename
    printf "|%s", ARGV[1]
    # the code section
    printf "|% 2d", section
    # separate table rows with a blank line
    print ""

    # reinit for next run...
    code = ""
    lines = 0
    start = 0
    fflush("/dev/stdout")
    next
}
# if start is set and we have not yet found its end: append line to the code
# variable and increment the code line counter
start { code = code "\n" $0 ; lines++ }
AWK

# find all templates and create a markdown table. first prints the markdown
# table header. NOTE: the markdown dialect is asciidoctor, because that allows
# table column definitions to span multiple lines
(
  echo ".Migration status"
  echo "|==="
  echo "python2|$PY2_COV|python3|$PY3_COV|diff py2 py3|# code lines|package|path|section"
  let total=0
  let success=0
  for F in $(find /etc/univention/templates/ -type f); do
     let total=$(expr $total + 1)
     PACKAGE=$(dpkg -S /etc/univention/templates/scripts/etc/postfix | cut -d: -f1)
     if awk -f /tmp/check-between.awk -v package="$PACKAGE" "$F"; then
       let success=$(expr $success + 1)
     fi
  done
  echo "|==="
  echo ""
  echo "== Summary =="
  echo $success/$total successful. limit: $SUCCESS_MIN.
  exit $(test $success -ge $SUCCESS_MIN)
) | tee /var/log/univention/$0.md
RETVAL=${PIPESTATUS[0]}
which asciidoctor && asciidoctor /var/log/univention/$0.md
exit $RETVAL

# vim:set ft=sh:awk:
